// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxklkekjltkyspvhnqbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94a2xrZWtqbHRreXNwdmhucWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5OTExMjUsImV4cCI6MjA1NTU2NzEyNX0.hhJ0-TdwnPIW15E9QK-GyKhiA0L9MT8sD2CNDy-FG4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);